- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - check-requirements
      - openstack-lower-constraints-jobs
      - build-openstack-docs-pti
    check:
      jobs:
        - build-openstack-releasenotes
    gate:
      jobs:
        - build-openstack-releasenotes
