#############################################################################
# Variables in body                                                         #
#############################################################################

hosts:  
  description: |
    Unique name of the host.
  in: body
  required: true
  type: list of strings
  min_version: 1

#############################################################################
# Variables in header                                                       #
#############################################################################

#############################################################################
# Variables in path                                                         #
#############################################################################

#############################################################################
# Variables in query                                                        #
#############################################################################
